doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '16'

        profiling_collect_backtrace: '%kernel.debug%'
    orm:
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        identity_generation_preferences:
            Doctrine\DBAL\Platforms\PostgreSQLPlatform: identity
        auto_mapping: true
        mappings:
            AppAccount:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Account/Entity'
                prefix: 'App\Account\Entity'
            AppCatalog:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Catalog/Entity'
                prefix: 'App\Catalog\Entity'
            AppInvoice:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Invoice/Entity'
                prefix: 'App\Invoice\Entity'
            AppMessaging:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Messaging/Entity'
                prefix: 'App\Messaging\Entity'
            AppPrestataire:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Prestataire/Entity'
                prefix: 'App\Prestataire\Entity'
            AppQuote:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Quote/Entity'
                prefix: 'App\Quote\Entity'
            AppReport:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Report/Entity'
                prefix: 'App\Report\Entity'
            AppReview:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Review/Entity'
                prefix: 'App\Review\Entity'
            AppSearch:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Search/Entity'
                prefix: 'App\Search\Entity'
            AppSubscription:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Subscription/Entity'
                prefix: 'App\Subscription\Entity'

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
