twig:
    file_name_pattern: '*.twig'
    globals:
        google_analytics_id: '%app.google_analytics_id%'
        google_tag_manager_id: '%app.google_tag_manager_id%'
when@test:
    twig:
        strict_variables: true
