vich_uploader:
    db_driver: orm

    mappings:
        company_logo:
            uri_prefix: /uploads/logos
            upload_destination: '%kernel.project_dir%/public/uploads/logos'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        company_cover:
            uri_prefix: /uploads/covers
            upload_destination: '%kernel.project_dir%/public/uploads/covers'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        company_signature:
            uri_prefix: /uploads/signatures
            upload_destination: '%kernel.project_dir%/public/uploads/signatures'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        user_avatars:
            uri_prefix: /uploads/avatars
            upload_destination: '%kernel.project_dir%/public/uploads/avatars'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        prestation_media:
            uri_prefix: /uploads/prestations
            upload_destination: '%kernel.project_dir%/public/uploads/prestations'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        message_attachments:
            uri_prefix: /uploads/messages
            upload_destination: '%kernel.project_dir%/public/uploads/messages'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_remove: true
            delete_on_update: true

        prestataire_documents:
            uri_prefix: /uploads/prestataire-documents
            upload_destination: '%kernel.project_dir%/public/uploads/prestataire-documents'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        quote_proposal_pdfs:
            upload_destination: '%kernel.project_dir%/var/uploads/quote-proposals/source'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_remove: true
            delete_on_update: true

        invoice_external_pdfs:
            upload_destination: '%kernel.project_dir%/var/uploads/invoices/source'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_remove: true
            delete_on_update: true
