<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260622102939 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE quote_request (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, description TEXT NOT NULL, budget_amount NUMERIC(10, 2) DEFAULT NULL, desired_date DATE DEFAULT NULL, status VARCHAR(50) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, client_id BIGINT NOT NULL, prestataire_id BIGINT DEFAULT NULL, prestation_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D478271B19EB6921 ON quote_request (client_id)');
        $this->addSql('CREATE INDEX IDX_D478271BBE3DB2B7 ON quote_request (prestataire_id)');
        $this->addSql('CREATE INDEX IDX_D478271B9E45C554 ON quote_request (prestation_id)');
        $this->addSql('ALTER TABLE quote_request ADD CONSTRAINT FK_D478271B19EB6921 FOREIGN KEY (client_id) REFERENCES client_profile (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE quote_request ADD CONSTRAINT FK_D478271BBE3DB2B7 FOREIGN KEY (prestataire_id) REFERENCES prestataire_profile (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE quote_request ADD CONSTRAINT FK_D478271B9E45C554 FOREIGN KEY (prestation_id) REFERENCES prestataire_profile_service (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE quote_request DROP CONSTRAINT FK_D478271B19EB6921');
        $this->addSql('ALTER TABLE quote_request DROP CONSTRAINT FK_D478271BBE3DB2B7');
        $this->addSql('ALTER TABLE quote_request DROP CONSTRAINT FK_D478271B9E45C554');
        $this->addSql('DROP TABLE quote_request');
    }
}
