<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260623072746 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE conversation (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, last_message_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_closed BOOLEAN DEFAULT false NOT NULL, quote_request_id BIGINT NOT NULL, client_id BIGINT NOT NULL, prestataire_id BIGINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8A8E26E9F229C21E ON conversation (quote_request_id)');
        $this->addSql('CREATE INDEX IDX_8A8E26E919EB6921 ON conversation (client_id)');
        $this->addSql('CREATE INDEX IDX_8A8E26E9BE3DB2B7 ON conversation (prestataire_id)');
        $this->addSql('ALTER TABLE conversation ADD CONSTRAINT FK_8A8E26E9F229C21E FOREIGN KEY (quote_request_id) REFERENCES quote_request (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE conversation ADD CONSTRAINT FK_8A8E26E919EB6921 FOREIGN KEY (client_id) REFERENCES client_profile (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE conversation ADD CONSTRAINT FK_8A8E26E9BE3DB2B7 FOREIGN KEY (prestataire_id) REFERENCES prestataire_profile (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE conversation DROP CONSTRAINT FK_8A8E26E9F229C21E');
        $this->addSql('ALTER TABLE conversation DROP CONSTRAINT FK_8A8E26E919EB6921');
        $this->addSql('ALTER TABLE conversation DROP CONSTRAINT FK_8A8E26E9BE3DB2B7');
        $this->addSql('DROP TABLE conversation');
    }
}
