<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260617130728 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE prestataire_availability (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, day_of_week INT NOT NULL, morning_enabled BOOLEAN DEFAULT false NOT NULL, morning_start TIME(0) WITHOUT TIME ZONE DEFAULT NULL, morning_end TIME(0) WITHOUT TIME ZONE DEFAULT NULL, afternoon_enabled BOOLEAN DEFAULT false NOT NULL, afternoon_start TIME(0) WITHOUT TIME ZONE DEFAULT NULL, afternoon_end TIME(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, prestataire_profile_id BIGINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_9624B58F1AE57984 ON prestataire_availability (prestataire_profile_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_prestataire_day ON prestataire_availability (prestataire_profile_id, day_of_week)');
        $this->addSql('ALTER TABLE prestataire_availability ADD CONSTRAINT FK_9624B58F1AE57984 FOREIGN KEY (prestataire_profile_id) REFERENCES prestataire_profile (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE prestataire_availability DROP CONSTRAINT FK_9624B58F1AE57984');
        $this->addSql('DROP TABLE prestataire_availability');
    }
}
