<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260707121648 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE prestataire_document (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(255) NOT NULL, status VARCHAR(255) NOT NULL, original_name VARCHAR(255) DEFAULT NULL, file_name VARCHAR(255) DEFAULT NULL, mime_type VARCHAR(100) DEFAULT NULL, file_size INT DEFAULT NULL, is_visible_to_client BOOLEAN DEFAULT false NOT NULL, issued_at DATE DEFAULT NULL, expires_at DATE DEFAULT NULL, notes TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, prestataire_profile_id BIGINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1C9DAC051AE57984 ON prestataire_document (prestataire_profile_id)');
        $this->addSql('ALTER TABLE prestataire_document ADD CONSTRAINT FK_1C9DAC051AE57984 FOREIGN KEY (prestataire_profile_id) REFERENCES prestataire_profile (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE prestataire_profile ALTER document_verification_status DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN prestataire_profile.document_verification_status IS \'\'');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE prestataire_document DROP CONSTRAINT FK_1C9DAC051AE57984');
        $this->addSql('DROP TABLE prestataire_document');
        $this->addSql('ALTER TABLE prestataire_profile ALTER document_verification_status SET DEFAULT \'NOT_SUBMITTED\'');
        $this->addSql('COMMENT ON COLUMN prestataire_profile.document_verification_status IS \'(DC2Type:App\\Enum\\DocumentVerificationStatusEnum)\'');
    }
}
