<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260618130002 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE prestataire_appointment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, starts_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, ends_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, status VARCHAR(30) NOT NULL, location_label VARCHAR(255) DEFAULT NULL, is_all_day BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, prestataire_id BIGINT NOT NULL, prestation_id INT DEFAULT NULL, client_id BIGINT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D1819BA8BE3DB2B7 ON prestataire_appointment (prestataire_id)');
        $this->addSql('CREATE INDEX IDX_D1819BA89E45C554 ON prestataire_appointment (prestation_id)');
        $this->addSql('CREATE INDEX IDX_D1819BA819EB6921 ON prestataire_appointment (client_id)');
        $this->addSql('ALTER TABLE prestataire_appointment ADD CONSTRAINT FK_D1819BA8BE3DB2B7 FOREIGN KEY (prestataire_id) REFERENCES prestataire_profile (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE prestataire_appointment ADD CONSTRAINT FK_D1819BA89E45C554 FOREIGN KEY (prestation_id) REFERENCES prestataire_profile_service (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE prestataire_appointment ADD CONSTRAINT FK_D1819BA819EB6921 FOREIGN KEY (client_id) REFERENCES client_profile (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE prestataire_appointment DROP CONSTRAINT FK_D1819BA8BE3DB2B7');
        $this->addSql('ALTER TABLE prestataire_appointment DROP CONSTRAINT FK_D1819BA89E45C554');
        $this->addSql('ALTER TABLE prestataire_appointment DROP CONSTRAINT FK_D1819BA819EB6921');
        $this->addSql('DROP TABLE prestataire_appointment');
    }
}
