<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260710071511 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE review (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, rating SMALLINT NOT NULL, comment TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, client_profile_id BIGINT NOT NULL, prestataire_profile_id BIGINT NOT NULL, quote_request_id BIGINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_review_client ON review (client_profile_id)');
        $this->addSql('CREATE INDEX idx_review_prestataire ON review (prestataire_profile_id)');
        $this->addSql('CREATE INDEX idx_review_created_at ON review (created_at)');
        $this->addSql('CREATE UNIQUE INDEX uniq_review_quote_request ON review (quote_request_id)');
        $this->addSql('ALTER TABLE review ADD CONSTRAINT FK_794381C65CAE2FF9 FOREIGN KEY (client_profile_id) REFERENCES client_profile (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE review ADD CONSTRAINT FK_794381C61AE57984 FOREIGN KEY (prestataire_profile_id) REFERENCES prestataire_profile (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE review ADD CONSTRAINT FK_794381C6F229C21E FOREIGN KEY (quote_request_id) REFERENCES quote_request (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE review DROP CONSTRAINT FK_794381C65CAE2FF9');
        $this->addSql('ALTER TABLE review DROP CONSTRAINT FK_794381C61AE57984');
        $this->addSql('ALTER TABLE review DROP CONSTRAINT FK_794381C6F229C21E');
        $this->addSql('DROP TABLE review');
    }
}
