<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260715123000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Ajoute le sous-domaine de signalement pour les demandes, conversations et avis.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE report (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, reporter_id BIGINT NOT NULL, reported_user_id BIGINT DEFAULT NULL, quote_request_id BIGINT DEFAULT NULL, conversation_id BIGINT DEFAULT NULL, review_id BIGINT DEFAULT NULL, reason VARCHAR(60) NOT NULL, message TEXT DEFAULT NULL, status VARCHAR(30) NOT NULL, admin_note TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, resolved_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_report_status ON report (status)');
        $this->addSql('CREATE INDEX idx_report_reason ON report (reason)');
        $this->addSql('CREATE INDEX idx_report_created_at ON report (created_at)');
        $this->addSql('CREATE INDEX IDX_C42F7784E1B89EFC ON report (reporter_id)');
        $this->addSql('CREATE INDEX IDX_C42F778450355193 ON report (reported_user_id)');
        $this->addSql('CREATE INDEX IDX_C42F778427DBA5A ON report (quote_request_id)');
        $this->addSql('CREATE INDEX IDX_C42F7784AC30FD62 ON report (conversation_id)');
        $this->addSql('CREATE INDEX IDX_C42F7784A76ED395 ON report (review_id)');
        $this->addSql('COMMENT ON COLUMN report.reason IS \'(DC2Type:App\\Enum\\ReportReasonEnum)\'');
        $this->addSql('COMMENT ON COLUMN report.status IS \'(DC2Type:App\\Enum\\ReportStatusEnum)\'');
        $this->addSql('ALTER TABLE report ADD CONSTRAINT FK_C42F7784E1B89EFC FOREIGN KEY (reporter_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE report ADD CONSTRAINT FK_C42F778450355193 FOREIGN KEY (reported_user_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE report ADD CONSTRAINT FK_C42F778427DBA5A FOREIGN KEY (quote_request_id) REFERENCES quote_request (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE report ADD CONSTRAINT FK_C42F7784AC30FD62 FOREIGN KEY (conversation_id) REFERENCES conversation (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE report ADD CONSTRAINT FK_C42F7784A76ED395 FOREIGN KEY (review_id) REFERENCES review (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE report DROP CONSTRAINT FK_C42F7784E1B89EFC');
        $this->addSql('ALTER TABLE report DROP CONSTRAINT FK_C42F778450355193');
        $this->addSql('ALTER TABLE report DROP CONSTRAINT FK_C42F778427DBA5A');
        $this->addSql('ALTER TABLE report DROP CONSTRAINT FK_C42F7784AC30FD62');
        $this->addSql('ALTER TABLE report DROP CONSTRAINT FK_C42F7784A76ED395');
        $this->addSql('DROP TABLE report');
    }
}
