<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260715103000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Ajoute les tarifs versionnés des plans d’abonnement et rattache chaque souscription au tarif réellement vendu.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('ALTER TABLE subscription_plan ADD stripe_product_id VARCHAR(255) DEFAULT NULL');

        $this->addSql('CREATE TABLE subscription_plan_price (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, plan_id BIGINT NOT NULL, billing_period VARCHAR(20) NOT NULL, label VARCHAR(120) DEFAULT NULL, amount NUMERIC(10, 2) NOT NULL, stripe_price_id VARCHAR(255) DEFAULT NULL, is_active BOOLEAN NOT NULL, is_promotional BOOLEAN NOT NULL, valid_from TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, valid_until TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_subscription_plan_price_stripe_price ON subscription_plan_price (stripe_price_id)');
        $this->addSql('CREATE INDEX idx_subscription_plan_price_plan_period ON subscription_plan_price (plan_id, billing_period)');
        $this->addSql('CREATE INDEX idx_subscription_plan_price_active ON subscription_plan_price (is_active)');
        $this->addSql('CREATE INDEX IDX_6D9668A7C182B004 ON subscription_plan_price (plan_id)');
        $this->addSql('COMMENT ON COLUMN subscription_plan_price.billing_period IS \'(DC2Type:App\\Enum\\SubscriptionBillingPeriodEnum)\'');
        $this->addSql('ALTER TABLE subscription_plan_price ADD CONSTRAINT FK_6D9668A7C182B004 FOREIGN KEY (plan_id) REFERENCES subscription_plan (id) ON DELETE CASCADE NOT DEFERRABLE');

        $this->addSql('ALTER TABLE prestataire_subscription ADD plan_price_id BIGINT DEFAULT NULL');
        $this->addSql('CREATE INDEX IDX_7D6BF1F72B3E1E3D ON prestataire_subscription (plan_price_id)');
        $this->addSql('ALTER TABLE prestataire_subscription ADD CONSTRAINT FK_7D6BF1F72B3E1E3D FOREIGN KEY (plan_price_id) REFERENCES subscription_plan_price (id) ON DELETE SET NULL NOT DEFERRABLE');

        $this->addSql("INSERT INTO subscription_plan_price (plan_id, billing_period, label, amount, stripe_price_id, is_active, is_promotional, valid_from, valid_until, created_at, updated_at)
            SELECT id, 'monthly', 'Tarif historique', monthly_amount, monthly_stripe_price_id, true, false, NULL, NULL, created_at, updated_at
            FROM subscription_plan
            WHERE monthly_amount IS NOT NULL");
        $this->addSql("INSERT INTO subscription_plan_price (plan_id, billing_period, label, amount, stripe_price_id, is_active, is_promotional, valid_from, valid_until, created_at, updated_at)
            SELECT id, 'annual', 'Tarif historique', annual_amount, annual_stripe_price_id, true, false, NULL, NULL, created_at, updated_at
            FROM subscription_plan
            WHERE annual_amount IS NOT NULL");

        $this->addSql("UPDATE prestataire_subscription ps
            SET plan_price_id = spp.id
            FROM subscription_plan_price spp
            WHERE ps.plan_id = spp.plan_id
              AND (
                (ps.stripe_price_id IS NOT NULL AND ps.stripe_price_id = spp.stripe_price_id)
                OR (
                    ps.stripe_price_id IS NULL
                    AND ps.billing_period = spp.billing_period
                    AND spp.is_promotional = false
                )
              )");
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE prestataire_subscription DROP CONSTRAINT FK_7D6BF1F72B3E1E3D');
        $this->addSql('DROP INDEX IDX_7D6BF1F72B3E1E3D');
        $this->addSql('ALTER TABLE prestataire_subscription DROP plan_price_id');

        $this->addSql('ALTER TABLE subscription_plan_price DROP CONSTRAINT FK_6D9668A7C182B004');
        $this->addSql('DROP TABLE subscription_plan_price');

        $this->addSql('ALTER TABLE subscription_plan DROP stripe_product_id');
    }
}
