<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260709103000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Ajoute le sous-domaine Subscription pour les abonnements Stripe, les crédits et les factures prestataire.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE subscription_plan (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(80) NOT NULL, name VARCHAR(180) NOT NULL, description TEXT DEFAULT NULL, monthly_amount NUMERIC(10, 2) DEFAULT NULL, annual_amount NUMERIC(10, 2) DEFAULT NULL, monthly_stripe_price_id VARCHAR(255) DEFAULT NULL, annual_stripe_price_id VARCHAR(255) DEFAULT NULL, monthly_credits INT NOT NULL, annual_credits INT NOT NULL, quote_responses_enabled BOOLEAN NOT NULL, instant_messaging_enabled BOOLEAN NOT NULL, sort_order INT NOT NULL, status VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_subscription_plan_code ON subscription_plan (code)');
        $this->addSql('CREATE UNIQUE INDEX uniq_subscription_plan_monthly_price ON subscription_plan (monthly_stripe_price_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_subscription_plan_annual_price ON subscription_plan (annual_stripe_price_id)');
        $this->addSql('CREATE INDEX idx_subscription_plan_status ON subscription_plan (status)');
        $this->addSql('CREATE INDEX idx_subscription_plan_sort_order ON subscription_plan (sort_order)');
        $this->addSql('COMMENT ON COLUMN subscription_plan.status IS \'(DC2Type:App\\Enum\\SubscriptionPlanStatusEnum)\'');

        $this->addSql('CREATE TABLE subscription_customer (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, prestataire_profile_id BIGINT NOT NULL, stripe_customer_id VARCHAR(255) NOT NULL, stripe_default_payment_method_id VARCHAR(255) DEFAULT NULL, default_payment_method_type VARCHAR(40) DEFAULT NULL, billing_email VARCHAR(180) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_subscription_customer_prestataire ON subscription_customer (prestataire_profile_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_subscription_customer_stripe_customer ON subscription_customer (stripe_customer_id)');
        $this->addSql('CREATE INDEX IDX_35BEE6C21AE57984 ON subscription_customer (prestataire_profile_id)');
        $this->addSql('ALTER TABLE subscription_customer ADD CONSTRAINT FK_35BEE6C21AE57984 FOREIGN KEY (prestataire_profile_id) REFERENCES prestataire_profile (id) ON DELETE CASCADE NOT DEFERRABLE');

        $this->addSql('CREATE TABLE prestataire_subscription (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, prestataire_profile_id BIGINT NOT NULL, customer_id BIGINT DEFAULT NULL, plan_id BIGINT DEFAULT NULL, billing_period VARCHAR(20) NOT NULL, status VARCHAR(30) NOT NULL, stripe_subscription_id VARCHAR(255) DEFAULT NULL, stripe_price_id VARCHAR(255) DEFAULT NULL, stripe_subscription_item_id VARCHAR(255) DEFAULT NULL, stripe_schedule_id VARCHAR(255) DEFAULT NULL, started_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, current_period_start TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, current_period_end TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, trial_starts_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, trial_ends_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, cancel_at_period_end BOOLEAN NOT NULL, cancellation_requested_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, canceled_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, ended_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, credits_granted_current_period INT NOT NULL, credits_consumed_current_period INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_prestataire_subscription_stripe_subscription ON prestataire_subscription (stripe_subscription_id)');
        $this->addSql('CREATE INDEX idx_prestataire_subscription_profile ON prestataire_subscription (prestataire_profile_id)');
        $this->addSql('CREATE INDEX idx_prestataire_subscription_status ON prestataire_subscription (status)');
        $this->addSql('CREATE INDEX idx_prestataire_subscription_period_end ON prestataire_subscription (current_period_end)');
        $this->addSql('CREATE INDEX IDX_7D6BF1F71AE57984 ON prestataire_subscription (prestataire_profile_id)');
        $this->addSql('CREATE INDEX IDX_7D6BF1F79395C3F3 ON prestataire_subscription (customer_id)');
        $this->addSql('CREATE INDEX IDX_7D6BF1F7C182B004 ON prestataire_subscription (plan_id)');
        $this->addSql('COMMENT ON COLUMN prestataire_subscription.billing_period IS \'(DC2Type:App\\Enum\\SubscriptionBillingPeriodEnum)\'');
        $this->addSql('COMMENT ON COLUMN prestataire_subscription.status IS \'(DC2Type:App\\Enum\\SubscriptionStatusEnum)\'');
        $this->addSql('ALTER TABLE prestataire_subscription ADD CONSTRAINT FK_7D6BF1F71AE57984 FOREIGN KEY (prestataire_profile_id) REFERENCES prestataire_profile (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE prestataire_subscription ADD CONSTRAINT FK_7D6BF1F79395C3F3 FOREIGN KEY (customer_id) REFERENCES subscription_customer (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE prestataire_subscription ADD CONSTRAINT FK_7D6BF1F7C182B004 FOREIGN KEY (plan_id) REFERENCES subscription_plan (id) ON DELETE SET NULL NOT DEFERRABLE');

        $this->addSql('CREATE TABLE subscription_invoice (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, subscription_id BIGINT DEFAULT NULL, stripe_invoice_id VARCHAR(255) NOT NULL, stripe_payment_intent_id VARCHAR(255) DEFAULT NULL, invoice_number VARCHAR(80) DEFAULT NULL, hosted_invoice_url VARCHAR(255) DEFAULT NULL, invoice_pdf_url VARCHAR(255) DEFAULT NULL, currency VARCHAR(3) NOT NULL, subtotal_amount NUMERIC(10, 2) DEFAULT NULL, tax_amount NUMERIC(10, 2) DEFAULT NULL, total_amount NUMERIC(10, 2) DEFAULT NULL, amount_paid NUMERIC(10, 2) DEFAULT NULL, amount_remaining NUMERIC(10, 2) DEFAULT NULL, status VARCHAR(20) NOT NULL, billing_reason VARCHAR(80) DEFAULT NULL, period_start TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, period_end TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, due_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, paid_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, stripe_payload JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_subscription_invoice_stripe_invoice ON subscription_invoice (stripe_invoice_id)');
        $this->addSql('CREATE INDEX idx_subscription_invoice_status ON subscription_invoice (status)');
        $this->addSql('CREATE INDEX idx_subscription_invoice_due_at ON subscription_invoice (due_at)');
        $this->addSql('CREATE INDEX IDX_48ADAE589A1887DC ON subscription_invoice (subscription_id)');
        $this->addSql('COMMENT ON COLUMN subscription_invoice.status IS \'(DC2Type:App\\Enum\\SubscriptionInvoiceStatusEnum)\'');
        $this->addSql('ALTER TABLE subscription_invoice ADD CONSTRAINT FK_48ADAE589A1887DC FOREIGN KEY (subscription_id) REFERENCES prestataire_subscription (id) ON DELETE SET NULL NOT DEFERRABLE');

        $this->addSql('CREATE TABLE subscription_credit_movement (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, prestataire_profile_id BIGINT NOT NULL, subscription_id BIGINT DEFAULT NULL, invoice_id BIGINT DEFAULT NULL, quote_request_id BIGINT DEFAULT NULL, type VARCHAR(40) NOT NULL, credits_delta INT NOT NULL, balance_after INT DEFAULT NULL, description VARCHAR(255) DEFAULT NULL, metadata JSON DEFAULT NULL, occurred_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_subscription_credit_movement_profile ON subscription_credit_movement (prestataire_profile_id)');
        $this->addSql('CREATE INDEX idx_subscription_credit_movement_type ON subscription_credit_movement (type)');
        $this->addSql('CREATE INDEX idx_subscription_credit_movement_occurred_at ON subscription_credit_movement (occurred_at)');
        $this->addSql('CREATE INDEX IDX_B8B5D97F1AE57984 ON subscription_credit_movement (prestataire_profile_id)');
        $this->addSql('CREATE INDEX IDX_B8B5D97F9A1887DC ON subscription_credit_movement (subscription_id)');
        $this->addSql('CREATE INDEX IDX_B8B5D97F2989F1FD ON subscription_credit_movement (invoice_id)');
        $this->addSql('CREATE INDEX IDX_B8B5D97F27DBA5A ON subscription_credit_movement (quote_request_id)');
        $this->addSql('COMMENT ON COLUMN subscription_credit_movement.type IS \'(DC2Type:App\\Enum\\SubscriptionCreditMovementTypeEnum)\'');
        $this->addSql('ALTER TABLE subscription_credit_movement ADD CONSTRAINT FK_B8B5D97F1AE57984 FOREIGN KEY (prestataire_profile_id) REFERENCES prestataire_profile (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE subscription_credit_movement ADD CONSTRAINT FK_B8B5D97F9A1887DC FOREIGN KEY (subscription_id) REFERENCES prestataire_subscription (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE subscription_credit_movement ADD CONSTRAINT FK_B8B5D97F2989F1FD FOREIGN KEY (invoice_id) REFERENCES subscription_invoice (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE subscription_credit_movement ADD CONSTRAINT FK_B8B5D97F27DBA5A FOREIGN KEY (quote_request_id) REFERENCES quote_request (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE subscription_credit_movement DROP CONSTRAINT FK_B8B5D97F1AE57984');
        $this->addSql('ALTER TABLE subscription_credit_movement DROP CONSTRAINT FK_B8B5D97F9A1887DC');
        $this->addSql('ALTER TABLE subscription_credit_movement DROP CONSTRAINT FK_B8B5D97F2989F1FD');
        $this->addSql('ALTER TABLE subscription_credit_movement DROP CONSTRAINT FK_B8B5D97F27DBA5A');
        $this->addSql('ALTER TABLE subscription_invoice DROP CONSTRAINT FK_48ADAE589A1887DC');
        $this->addSql('ALTER TABLE prestataire_subscription DROP CONSTRAINT FK_7D6BF1F71AE57984');
        $this->addSql('ALTER TABLE prestataire_subscription DROP CONSTRAINT FK_7D6BF1F79395C3F3');
        $this->addSql('ALTER TABLE prestataire_subscription DROP CONSTRAINT FK_7D6BF1F7C182B004');
        $this->addSql('ALTER TABLE subscription_customer DROP CONSTRAINT FK_35BEE6C21AE57984');
        $this->addSql('DROP TABLE subscription_credit_movement');
        $this->addSql('DROP TABLE subscription_invoice');
        $this->addSql('DROP TABLE prestataire_subscription');
        $this->addSql('DROP TABLE subscription_customer');
        $this->addSql('DROP TABLE subscription_plan');
    }
}
