<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260627105905 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create notification table for in-app user notifications';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE notification (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(50) NOT NULL, title VARCHAR(255) NOT NULL, body TEXT NOT NULL, target_url VARCHAR(255) DEFAULT NULL, is_read BOOLEAN DEFAULT false NOT NULL, read_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, metadata JSON DEFAULT NULL, recipient_id BIGINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_notification_recipient ON notification (recipient_id)');
        $this->addSql('CREATE INDEX idx_notification_type ON notification (type)');
        $this->addSql('CREATE INDEX idx_notification_recipient_is_read ON notification (recipient_id, is_read)');
        $this->addSql('CREATE INDEX idx_notification_recipient_created_at ON notification (recipient_id, created_at)');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_BF5476CAE92F8F78 FOREIGN KEY (recipient_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE notification DROP CONSTRAINT FK_BF5476CAE92F8F78');
        $this->addSql('DROP TABLE notification');
    }
}
