<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260609075039 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE prestataire_profile_service DROP CONSTRAINT fk_7acde71fed5ca9e6');
        $this->addSql('ALTER TABLE prestataire_profile_service DROP CONSTRAINT fk_7acde71f1ae57984');
        $this->addSql('ALTER TABLE prestataire_profile_service DROP CONSTRAINT prestataire_profile_service_pkey');
        $this->addSql('ALTER TABLE prestataire_profile_service ADD id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL');
        $this->addSql('ALTER TABLE prestataire_profile_service ADD prix_catalogue NUMERIC(10, 2) DEFAULT 0 NOT NULL');
        $this->addSql('ALTER TABLE prestataire_profile_service ADD taux_reduction NUMERIC(5, 2) DEFAULT NULL');
        $this->addSql('ALTER TABLE prestataire_profile_service ADD CONSTRAINT FK_7ACDE71FED5CA9E6 FOREIGN KEY (service_id) REFERENCES service (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE prestataire_profile_service ADD CONSTRAINT FK_7ACDE71F1AE57984 FOREIGN KEY (prestataire_profile_id) REFERENCES prestataire_profile (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE prestataire_profile_service ADD PRIMARY KEY (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE prestataire_profile_service DROP CONSTRAINT FK_7ACDE71F1AE57984');
        $this->addSql('ALTER TABLE prestataire_profile_service DROP CONSTRAINT FK_7ACDE71FED5CA9E6');
        $this->addSql('ALTER TABLE prestataire_profile_service DROP CONSTRAINT prestataire_profile_service_pkey');
        $this->addSql('ALTER TABLE prestataire_profile_service DROP id');
        $this->addSql('ALTER TABLE prestataire_profile_service DROP prix_catalogue');
        $this->addSql('ALTER TABLE prestataire_profile_service DROP taux_reduction');
        $this->addSql('ALTER TABLE prestataire_profile_service ADD CONSTRAINT fk_7acde71f1ae57984 FOREIGN KEY (prestataire_profile_id) REFERENCES prestataire_profile (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE prestataire_profile_service ADD CONSTRAINT fk_7acde71fed5ca9e6 FOREIGN KEY (service_id) REFERENCES service (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE prestataire_profile_service ADD PRIMARY KEY (prestataire_profile_id, service_id)');
    }
}
