<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260527134630 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE client_profile (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(50) NOT NULL, company_name VARCHAR(255) DEFAULT NULL, siret VARCHAR(14) DEFAULT NULL, billing_address VARCHAR(255) DEFAULT NULL, billing_postal_code VARCHAR(20) DEFAULT NULL, billing_city VARCHAR(100) DEFAULT NULL, billing_country VARCHAR(100) DEFAULT NULL, default_address VARCHAR(255) DEFAULT NULL, default_postal_code VARCHAR(20) DEFAULT NULL, default_city VARCHAR(100) DEFAULT NULL, latitude NUMERIC(10, 7) DEFAULT NULL, longitude NUMERIC(10, 7) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id BIGINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D36AEE72A76ED395 ON client_profile (user_id)');
        $this->addSql('CREATE TABLE prestataire_profile (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, company_name VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, legal_name VARCHAR(255) DEFAULT NULL, structure_type VARCHAR(80) DEFAULT NULL, siren VARCHAR(9) DEFAULT NULL, siret VARCHAR(14) DEFAULT NULL, vat_number VARCHAR(50) DEFAULT NULL, address VARCHAR(255) DEFAULT NULL, address_complement VARCHAR(255) DEFAULT NULL, postal_code VARCHAR(20) DEFAULT NULL, city VARCHAR(100) DEFAULT NULL, country VARCHAR(100) DEFAULT NULL, latitude NUMERIC(10, 7) DEFAULT NULL, longitude NUMERIC(10, 7) DEFAULT NULL, geohash VARCHAR(20) DEFAULT NULL, phone_public VARCHAR(30) DEFAULT NULL, phone_private VARCHAR(30) DEFAULT NULL, website VARCHAR(255) DEFAULT NULL, facebook_url VARCHAR(255) DEFAULT NULL, instagram_url VARCHAR(255) DEFAULT NULL, linkedin_url VARCHAR(255) DEFAULT NULL, short_description VARCHAR(500) DEFAULT NULL, long_description TEXT DEFAULT NULL, logo VARCHAR(255) DEFAULT NULL, cover_image VARCHAR(255) DEFAULT NULL, profile_status VARCHAR(50) NOT NULL, verification_status VARCHAR(50) NOT NULL, completion_score INT NOT NULL, average_rating NUMERIC(3, 2) NOT NULL, reviews_count INT NOT NULL, response_time_minutes INT DEFAULT NULL, is_featured BOOLEAN NOT NULL, featured_until TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, search_visibility VARCHAR(50) NOT NULL, verified_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id BIGINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_143B61F6989D9B62 ON prestataire_profile (slug)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_143B61F626E94372 ON prestataire_profile (siret)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_143B61F6A76ED395 ON prestataire_profile (user_id)');
        $this->addSql('CREATE TABLE "user" (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, first_name VARCHAR(100) DEFAULT NULL, last_name VARCHAR(100) DEFAULT NULL, phone_number VARCHAR(30) DEFAULT NULL, phone_verified_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, email_verified_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_verified BOOLEAN NOT NULL, avatar VARCHAR(255) DEFAULT NULL, locale VARCHAR(10) DEFAULT NULL, timezone VARCHAR(100) DEFAULT NULL, status VARCHAR(50) NOT NULL, last_login_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, login_count INT NOT NULL, reset_token VARCHAR(255) DEFAULT NULL, reset_token_expires_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE client_profile ADD CONSTRAINT FK_D36AEE72A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE prestataire_profile ADD CONSTRAINT FK_143B61F6A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE client_profile DROP CONSTRAINT FK_D36AEE72A76ED395');
        $this->addSql('ALTER TABLE prestataire_profile DROP CONSTRAINT FK_143B61F6A76ED395');
        $this->addSql('DROP TABLE client_profile');
        $this->addSql('DROP TABLE prestataire_profile');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
