<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260611063353 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE prestataire_intervention_zone (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, city VARCHAR(100) DEFAULT NULL, postal_code VARCHAR(20) DEFAULT NULL, department VARCHAR(100) DEFAULT NULL, region VARCHAR(100) DEFAULT NULL, latitude NUMERIC(10, 7) DEFAULT NULL, longitude NUMERIC(10, 7) DEFAULT NULL, radius_km INT DEFAULT NULL, is_main_zone BOOLEAN DEFAULT NULL, is_active BOOLEAN DEFAULT NULL, prestataire_profile_id BIGINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_432B0E6C1AE57984 ON prestataire_intervention_zone (prestataire_profile_id)');
        $this->addSql('ALTER TABLE prestataire_intervention_zone ADD CONSTRAINT FK_432B0E6C1AE57984 FOREIGN KEY (prestataire_profile_id) REFERENCES prestataire_profile (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE prestataire_intervention_zone DROP CONSTRAINT FK_432B0E6C1AE57984');
        $this->addSql('DROP TABLE prestataire_intervention_zone');
    }
}
