<?php

namespace App\Enum;

enum VerificationStatusEnum: string
{
    case NOT_VERIFIED = 'NOT_VERIFIED';
    case EMAIL_VERIFIED = 'EMAIL_VERIFIED';
    case PHONE_VERIFIED = 'PHONE_VERIFIED';
    case COMPANY_VERIFIED = 'COMPANY_VERIFIED';
    case DOCUMENTS_VERIFIED = 'DOCUMENTS_VERIFIED';
    case MANUALLY_VERIFIED = 'MANUALLY_VERIFIED';
}