<?php

/**
 * Copyright(c) 2026 Trouve moi
 *
 * Ce fichier fait partie d’un projet développé par Auxioma Web Agency.
 * Tous droits réservés.
 *
 * Ce code source est la propriété exclusive de Auxioma Web Agency.
 * Toute reproduction, modification, distribution ou utilisation sans autorisation préalable est interdite.
 */

namespace App\DataFixtures\Prestataire;

use App\DataFixtures\User\PrestataireUserFixtures;
use App\Entity\PrestataireProfile;
use App\Entity\User;
use App\Enum\PrestataireProfileStatusEnum;
use App\Enum\SearchVisibilityEnum;
use App\Enum\VerificationStatusEnum;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Common\DataFixtures\DependentFixtureInterface;
use Doctrine\Persistence\ObjectManager;
use Symfony\Component\String\Slugger\SluggerInterface;

class PrestataireProfileFixtures extends Fixture implements DependentFixtureInterface
{
    public const PROFILE_ALAIN_REFERENCE = 'profile_prestataire_alain';
    public const PROFILE_MARIO_REFERENCE = 'profile_prestataire_mario';
    public const PROFILE_CAMILLE_REFERENCE = 'profile_prestataire_camille';
    public const PROFILE_JULIE_REFERENCE = 'profile_prestataire_julie';
    public const PROFILE_THOMAS_REFERENCE = 'profile_prestataire_thomas';
    public const PROFILE_SONIA_REFERENCE = 'profile_prestataire_sonia';
    public const PROFILE_JESSICA_REFERENCE = 'profile_prestataire_jessica';
    public const PROFILE_NADIA_REFERENCE = 'profile_prestataire_nadia';
    public const PROFILE_PIERRE_REFERENCE = 'profile_prestataire_pierre';
    public const PROFILE_KEVIN_REFERENCE = 'profile_prestataire_kevin';
    public const PROFILE_CLARA_REFERENCE = 'profile_prestataire_clara';
    public const PROFILE_HUGO_REFERENCE = 'profile_prestataire_hugo';
    public const PROFILE_EMMA_REFERENCE = 'profile_prestataire_emma';
    public const PROFILE_YASSINE_REFERENCE = 'profile_prestataire_yassine';
    public const PROFILE_LAURA_REFERENCE = 'profile_prestataire_laura';
    public const PROFILE_MATTHIEU_REFERENCE = 'profile_prestataire_matthieu';
    public const PROFILE_CHLOE_REFERENCE = 'profile_prestataire_chloe';
    public const PROFILE_ENZO_REFERENCE = 'profile_prestataire_enzo';
    public const PROFILE_INES_REFERENCE = 'profile_prestataire_ines';
    public const PROFILE_SARAH_REFERENCE = 'profile_prestataire_sarah';

    public function __construct(
        private SluggerInterface $slugger,
    ) {
    }

    public function load(ObjectManager $manager): void
    {
        $now = new \DateTimeImmutable();

        $profiles = [
            [
                'reference' => self::PROFILE_ALAIN_REFERENCE,
                'user_reference' => PrestataireUserFixtures::PRESTA_ALAIN_REFERENCE,
                'company_name' => 'BT Confort',
                'legal_name' => 'BT Confort Rénovation',
                'structure_type' => 'SARL',
                'siren' => '804123451',
                'siret' => '80412345100011',
                'vat_number' => 'FR69804123451',
                'metier' => 'Électricien',
                'experience' => '12 ans d’expérience',
                'address' => '12 rue des Menuisiers',
                'postal_code' => '33000',
                'city' => 'Bordeaux',
                'country' => 'France',
                'latitude' => '44.8377890',
                'longitude' => '-0.5791800',
                'geohash' => 'ezyzh4',
                'phone_public' => '0556001001',
                'phone_private' => '0610010001',
                'website' => 'https://www.bt-confort.fr',
                'facebook_url' => 'https://facebook.com/btconfort',
                'instagram_url' => 'https://instagram.com/btconfort',
                'linkedin_url' => 'https://linkedin.com/company/bt-confort',
                'short_description' => 'Travaux électriques et remise aux normes pour logements et locaux.',
                'long_description' => 'BT Confort accompagne particuliers et professionnels pour leurs installations électriques, remises aux normes, tableaux, prises et interventions rapides en Gironde. Nous privilégions des interventions propres, pédagogiques et durables.',
                'description' => 'Entreprise locale spécialisée en électricité générale, rénovation et dépannage.',
                'average_rating' => '4.80',
                'reviews_count' => 31,
                'response_time_minutes' => 38,
                'completion_score' => 94,
                'verification_status' => VerificationStatusEnum::MANUALLY_VERIFIED,
                'verified_at' => $now->modify('-8 months'),
                'search_visibility' => SearchVisibilityEnum::PREMIUM,
                'is_featured' => true,
                'featured_until' => $now->modify('+20 days'),
            ],
            [
                'reference' => self::PROFILE_MARIO_REFERENCE,
                'user_reference' => PrestataireUserFixtures::PRESTA_MARIO_REFERENCE,
                'company_name' => 'Plomberie Bros & Co',
                'legal_name' => 'Plomberie Bros & Co',
                'structure_type' => 'SASU',
                'siren' => '804123452',
                'siret' => '80412345200019',
                'vat_number' => 'FR61804123452',
                'metier' => 'Plombier Chauffagiste',
                'experience' => '15 ans d’expérience',
                'address' => '18 avenue de la Marne',
                'postal_code' => '33200',
                'city' => 'Bordeaux',
                'country' => 'France',
                'latitude' => '44.8562000',
                'longitude' => '-0.6208000',
                'geohash' => 'ezynzj',
                'phone_public' => '0556001002',
                'phone_private' => '0610010002',
                'website' => 'https://www.plomberiebros.fr',
                'facebook_url' => 'https://facebook.com/plomberiebros',
                'instagram_url' => 'https://instagram.com/plomberiebros',
                'linkedin_url' => 'https://linkedin.com/company/plomberie-bros',
                'short_description' => 'Dépannage plomberie et installation sanitaire rapide.',
                'long_description' => 'Plomberie Bros & Co intervient sur les fuites, chauffe-eau, débouchages, rénovations de salle de bain et petits travaux sanitaires avec un haut niveau de disponibilité.',
                'description' => 'Interventions rapides en plomberie, chauffage et salle de bain.',
                'average_rating' => '4.90',
                'reviews_count' => 46,
                'response_time_minutes' => 24,
                'completion_score' => 97,
                'verification_status' => VerificationStatusEnum::DOCUMENTS_VERIFIED,
                'verified_at' => $now->modify('-6 months'),
                'search_visibility' => SearchVisibilityEnum::BOOSTED,
                'is_featured' => true,
                'featured_until' => $now->modify('+14 days'),
            ],
            [
                'reference' => self::PROFILE_CAMILLE_REFERENCE,
                'user_reference' => PrestataireUserFixtures::PRESTA_CAMILLE_REFERENCE,
                'company_name' => 'Jardin Design',
                'legal_name' => 'Jardin Design Services',
                'structure_type' => 'EI',
                'siren' => '804123453',
                'siret' => '80412345300027',
                'vat_number' => 'FR89804123453',
                'metier' => 'Jardinier paysagiste',
                'experience' => '8 ans d’expérience',
                'address' => '6 chemin des Vignes',
                'postal_code' => '33610',
                'city' => 'Cestas',
                'country' => 'France',
                'latitude' => '44.7445000',
                'longitude' => '-0.6835000',
                'geohash' => 'ezyn6g',
                'phone_public' => '0556001003',
                'phone_private' => '0610010003',
                'website' => 'https://www.jardin-design.fr',
                'facebook_url' => 'https://facebook.com/jardindesign33',
                'instagram_url' => 'https://instagram.com/jardindesign33',
                'linkedin_url' => 'https://linkedin.com/company/jardin-design',
                'short_description' => 'Entretien, taille et aménagement paysager sur mesure.',
                'long_description' => 'Camille intervient auprès des particuliers et résidences pour l’entretien des espaces verts, la création d’aménagements extérieurs et le suivi saisonnier des jardins.',
                'description' => 'Paysagisme, entretien courant et petits aménagements extérieurs.',
                'average_rating' => '4.70',
                'reviews_count' => 19,
                'response_time_minutes' => 52,
                'completion_score' => 90,
                'verification_status' => VerificationStatusEnum::COMPANY_VERIFIED,
                'verified_at' => $now->modify('-5 months'),
                'search_visibility' => SearchVisibilityEnum::NORMAL,
                'is_featured' => false,
                'featured_until' => null,
            ],
            [
                'reference' => self::PROFILE_JULIE_REFERENCE,
                'user_reference' => PrestataireUserFixtures::PRESTA_JULIE_REFERENCE,
                'company_name' => 'Nature Jardins',
                'legal_name' => 'Nature Jardins & Extérieurs',
                'structure_type' => 'SARL',
                'siren' => '804123454',
                'siret' => '80412345400035',
                'vat_number' => 'FR24804123454',
                'metier' => 'Paysagiste',
                'experience' => '10 ans d’expérience',
                'address' => '9 allée des Dunes',
                'postal_code' => '33680',
                'city' => 'Lacanau',
                'country' => 'France',
                'latitude' => '45.0023000',
                'longitude' => '-1.2030000',
                'geohash' => 'ezz1ub',
                'phone_public' => '0556001004',
                'phone_private' => '0610010004',
                'website' => 'https://www.nature-jardins.fr',
                'facebook_url' => 'https://facebook.com/naturejardins',
                'instagram_url' => 'https://instagram.com/naturejardins',
                'linkedin_url' => 'https://linkedin.com/company/nature-jardins',
                'short_description' => 'Création et entretien de jardins en bord de mer.',
                'long_description' => 'Nature Jardins conçoit, entretient et valorise les extérieurs avec une approche adaptée aux sols sableux et aux contraintes climatiques du littoral.',
                'description' => 'Paysagisme et entretien d’espaces verts autour de Lacanau.',
                'average_rating' => '4.75',
                'reviews_count' => 24,
                'response_time_minutes' => 43,
                'completion_score' => 93,
                'verification_status' => VerificationStatusEnum::MANUALLY_VERIFIED,
                'verified_at' => $now->modify('-7 months'),
                'search_visibility' => SearchVisibilityEnum::BOOSTED,
                'is_featured' => true,
                'featured_until' => $now->modify('+10 days'),
            ],
            [
                'reference' => self::PROFILE_THOMAS_REFERENCE,
                'user_reference' => PrestataireUserFixtures::PRESTA_THOMAS_REFERENCE,
                'company_name' => 'Avenir Numérique',
                'legal_name' => 'Avenir Numérique Studio',
                'structure_type' => 'SAS',
                'siren' => '804123455',
                'siret' => '80412345500043',
                'vat_number' => 'FR53804123455',
                'metier' => 'Développeur Web',
                'experience' => '9 ans d’expérience',
                'address' => '22 rue du Professeur Calmette',
                'postal_code' => '33170',
                'city' => 'Gradignan',
                'country' => 'France',
                'latitude' => '44.7727000',
                'longitude' => '-0.6110000',
                'geohash' => 'ezyn7x',
                'phone_public' => '0556001005',
                'phone_private' => '0610010005',
                'website' => 'https://www.avenir-numerique.fr',
                'facebook_url' => 'https://facebook.com/avenirnumerique',
                'instagram_url' => 'https://instagram.com/avenirnumerique',
                'linkedin_url' => 'https://linkedin.com/company/avenir-numerique',
                'short_description' => 'Sites vitrines, e-commerce et optimisation SEO.',
                'long_description' => 'Avenir Numérique conçoit des sites performants, modernes et pensés pour la conversion. L’accompagnement inclut cadrage, UX, SEO local, maintenance et conseil technique.',
                'description' => 'Création de sites web pour indépendants, TPE et PME.',
                'average_rating' => '4.95',
                'reviews_count' => 28,
                'response_time_minutes' => 70,
                'completion_score' => 98,
                'verification_status' => VerificationStatusEnum::DOCUMENTS_VERIFIED,
                'verified_at' => $now->modify('-4 months'),
                'search_visibility' => SearchVisibilityEnum::PREMIUM,
                'is_featured' => true,
                'featured_until' => $now->modify('+25 days'),
            ],
            [
                'reference' => self::PROFILE_SONIA_REFERENCE,
                'user_reference' => PrestataireUserFixtures::PRESTA_SONIA_REFERENCE,
                'company_name' => 'Assistance Digital',
                'legal_name' => 'Assistance Digital Services',
                'structure_type' => 'EI',
                'siren' => '804123456',
                'siret' => '80412345600050',
                'vat_number' => 'FR92804123456',
                'metier' => 'Technicienne informatique',
                'experience' => '7 ans d’expérience',
                'address' => '31 avenue du Médoc',
                'postal_code' => '33320',
                'city' => 'Eysines',
                'country' => 'France',
                'latitude' => '44.8858000',
                'longitude' => '-0.6513000',
                'geohash' => 'ezynzw',
                'phone_public' => '0556001006',
                'phone_private' => '0610010006',
                'website' => 'https://www.assistance-digital.fr',
                'facebook_url' => 'https://facebook.com/assistancedigital33',
                'instagram_url' => 'https://instagram.com/assistancedigital33',
                'linkedin_url' => 'https://linkedin.com/company/assistance-digital',
                'short_description' => 'Assistance informatique à domicile et dépannage PC/Mac.',
                'long_description' => 'Sonia aide les particuliers et petites structures sur les pannes courantes, la sécurité, le Wi-Fi, les réinstallations et la prise en main numérique.',
                'description' => 'Support informatique de proximité, clair et réactif.',
                'average_rating' => '4.60',
                'reviews_count' => 17,
                'response_time_minutes' => 55,
                'completion_score' => 89,
                'verification_status' => VerificationStatusEnum::PHONE_VERIFIED,
                'verified_at' => $now->modify('-3 months'),
                'search_visibility' => SearchVisibilityEnum::NORMAL,
                'is_featured' => false,
                'featured_until' => null,
            ],
            [
                'reference' => self::PROFILE_JESSICA_REFERENCE,
                'user_reference' => PrestataireUserFixtures::PRESTA_JESSICA_REFERENCE,
                'company_name' => 'Clean Services',
                'legal_name' => 'Clean Services Habitat',
                'structure_type' => 'SASU',
                'siren' => '804123457',
                'siret' => '80412345700068',
                'vat_number' => 'FR44804123457',
                'metier' => 'Agent d’entretien',
                'experience' => '6 ans d’expérience',
                'address' => '14 rue de la Verrerie',
                'postal_code' => '33700',
                'city' => 'Mérignac',
                'country' => 'France',
                'latitude' => '44.8422000',
                'longitude' => '-0.6457000',
                'geohash' => 'ezynpu',
                'phone_public' => '0556001007',
                'phone_private' => '0610010007',
                'website' => 'https://www.clean-services.fr',
                'facebook_url' => 'https://facebook.com/cleanservices33',
                'instagram_url' => 'https://instagram.com/cleanservices33',
                'linkedin_url' => 'https://linkedin.com/company/clean-services',
                'short_description' => 'Ménage régulier, remise en état et lavage de vitres.',
                'long_description' => 'Jessica propose des prestations d’entretien fiables pour résidences principales, locations saisonnières et petits bureaux avec des créneaux souples.',
                'description' => 'Services d’entretien pour particuliers et professionnels.',
                'average_rating' => '4.65',
                'reviews_count' => 22,
                'response_time_minutes' => 48,
                'completion_score' => 92,
                'verification_status' => VerificationStatusEnum::EMAIL_VERIFIED,
                'verified_at' => $now->modify('-2 months'),
                'search_visibility' => SearchVisibilityEnum::NORMAL,
                'is_featured' => false,
                'featured_until' => null,
            ],
            [
                'reference' => self::PROFILE_NADIA_REFERENCE,
                'user_reference' => PrestataireUserFixtures::PRESTA_NADIA_REFERENCE,
                'company_name' => 'Aide Domicile Plus',
                'legal_name' => 'Aide Domicile Plus',
                'structure_type' => 'Association',
                'siren' => '804123458',
                'siret' => '80412345800076',
                'vat_number' => 'FR10804123458',
                'metier' => 'Assistante de vie',
                'experience' => '11 ans d’expérience',
                'address' => '27 rue Armand Caduc',
                'postal_code' => '33130',
                'city' => 'Bègles',
                'country' => 'France',
                'latitude' => '44.8077000',
                'longitude' => '-0.5489000',
                'geohash' => 'ezynm6',
                'phone_public' => '0556001008',
                'phone_private' => '0610010008',
                'website' => 'https://www.aide-domicile-plus.fr',
                'facebook_url' => 'https://facebook.com/aidedomicileplus',
                'instagram_url' => 'https://instagram.com/aidedomicileplus',
                'linkedin_url' => 'https://linkedin.com/company/aide-domicile-plus',
                'short_description' => 'Accompagnement du quotidien et aide à domicile.',
                'long_description' => 'Nadia intervient avec sérieux et bienveillance pour l’accompagnement à domicile, les besoins du quotidien et le soutien aux familles.',
                'description' => 'Aide à domicile humaine, fiable et organisée.',
                'average_rating' => '4.85',
                'reviews_count' => 26,
                'response_time_minutes' => 40,
                'completion_score' => 95,
                'verification_status' => VerificationStatusEnum::COMPANY_VERIFIED,
                'verified_at' => $now->modify('-9 months'),
                'search_visibility' => SearchVisibilityEnum::BOOSTED,
                'is_featured' => true,
                'featured_until' => $now->modify('+12 days'),
            ],
            [
                'reference' => self::PROFILE_PIERRE_REFERENCE,
                'user_reference' => PrestataireUserFixtures::PRESTA_PIERRE_REFERENCE,
                'company_name' => 'Méca Dépannage',
                'legal_name' => 'Méca Dépannage 17',
                'structure_type' => 'SARL',
                'siren' => '804123459',
                'siret' => '80412345900084',
                'vat_number' => 'FR57804123459',
                'metier' => 'Mécanicien auto',
                'experience' => '13 ans d’expérience',
                'address' => '44 boulevard Mestrezat',
                'postal_code' => '33120',
                'city' => 'Arcachon',
                'country' => 'France',
                'latitude' => '44.6615000',
                'longitude' => '-1.1725000',
                'geohash' => 'ezymyp',
                'phone_public' => '0556001009',
                'phone_private' => '0610010009',
                'website' => 'https://www.meca-depannage.fr',
                'facebook_url' => 'https://facebook.com/mecadepannage17',
                'instagram_url' => 'https://instagram.com/mecadepannage17',
                'linkedin_url' => 'https://linkedin.com/company/meca-depannage',
                'short_description' => 'Entretien auto, freinage et diagnostic de panne.',
                'long_description' => 'Pierre prend en charge l’entretien courant automobile, les diagnostics mécaniques et les petites réparations avec un excellent rapport clarté/efficacité.',
                'description' => 'Garage de proximité spécialisé en mécanique rapide.',
                'average_rating' => '4.72',
                'reviews_count' => 34,
                'response_time_minutes' => 47,
                'completion_score' => 94,
                'verification_status' => VerificationStatusEnum::DOCUMENTS_VERIFIED,
                'verified_at' => $now->modify('-10 months'),
                'search_visibility' => SearchVisibilityEnum::BOOSTED,
                'is_featured' => false,
                'featured_until' => null,
            ],
            [
                'reference' => self::PROFILE_KEVIN_REFERENCE,
                'user_reference' => PrestataireUserFixtures::PRESTA_KEVIN_REFERENCE,
                'company_name' => 'Atelier 2 Roues',
                'legal_name' => 'Atelier 2 Roues Services',
                'structure_type' => 'EI',
                'siren' => '804123460',
                'siret' => '80412346000092',
                'vat_number' => 'FR05804123460',
                'metier' => 'Mécanicien deux-roues',
                'experience' => '5 ans d’expérience',
                'address' => '5 rue des Frères Lumière',
                'postal_code' => '33470',
                'city' => 'Gujan-Mestras',
                'country' => 'France',
                'latitude' => '44.6356000',
                'longitude' => '-1.0710000',
                'geohash' => 'ezymyt',
                'phone_public' => '0556001010',
                'phone_private' => '0610010010',
                'website' => 'https://www.atelier2roues.fr',
                'facebook_url' => 'https://facebook.com/atelier2roues',
                'instagram_url' => 'https://instagram.com/atelier2roues',
                'linkedin_url' => 'https://linkedin.com/company/atelier-2-roues',
                'short_description' => 'Entretien moto, vélo électrique et révision rapide.',
                'long_description' => 'Kevin accompagne les particuliers sur l’entretien courant des deux-roues avec des interventions simples, transparentes et pédagogiques.',
                'description' => 'Spécialiste des deux-roues thermiques et électriques.',
                'average_rating' => '4.52',
                'reviews_count' => 15,
                'response_time_minutes' => 58,
                'completion_score' => 86,
                'verification_status' => VerificationStatusEnum::PHONE_VERIFIED,
                'verified_at' => $now->modify('-45 days'),
                'search_visibility' => SearchVisibilityEnum::NORMAL,
                'is_featured' => false,
                'featured_until' => null,
            ],
            [
                'reference' => self::PROFILE_CLARA_REFERENCE,
                'user_reference' => PrestataireUserFixtures::PRESTA_CLARA_REFERENCE,
                'company_name' => 'Instant Fête',
                'legal_name' => 'Instant Fête Organisation',
                'structure_type' => 'SASU',
                'siren' => '804123461',
                'siret' => '80412346100027',
                'vat_number' => 'FR36804123461',
                'metier' => 'Organisatrice événementielle',
                'experience' => '8 ans d’expérience',
                'address' => '2 place Tourny',
                'postal_code' => '33000',
                'city' => 'Bordeaux',
                'country' => 'France',
                'latitude' => '44.8446000',
                'longitude' => '-0.5753000',
                'geohash' => 'ezyzh7',
                'phone_public' => '0556001011',
                'phone_private' => '0610010011',
                'website' => 'https://www.instant-fete.fr',
                'facebook_url' => 'https://facebook.com/instantfete',
                'instagram_url' => 'https://instagram.com/instantfete',
                'linkedin_url' => 'https://linkedin.com/company/instant-fete',
                'short_description' => 'Organisation d’événements privés et pro clés en main.',
                'long_description' => 'Clara coordonne mariage, anniversaire, inauguration et petits événements d’entreprise avec un solide réseau de prestataires partenaires.',
                'description' => 'Cheffe de projet événementielle réactive et structurée.',
                'average_rating' => '4.88',
                'reviews_count' => 21,
                'response_time_minutes' => 62,
                'completion_score' => 95,
                'verification_status' => VerificationStatusEnum::COMPANY_VERIFIED,
                'verified_at' => $now->modify('-11 months'),
                'search_visibility' => SearchVisibilityEnum::PREMIUM,
                'is_featured' => true,
                'featured_until' => $now->modify('+18 days'),
            ],
            [
                'reference' => self::PROFILE_HUGO_REFERENCE,
                'user_reference' => PrestataireUserFixtures::PRESTA_HUGO_REFERENCE,
                'company_name' => 'Studio Événement',
                'legal_name' => 'Studio Événement & Sonorisation',
                'structure_type' => 'SAS',
                'siren' => '804123462',
                'siret' => '80412346200035',
                'vat_number' => 'FR77804123462',
                'metier' => 'Photographe événementiel',
                'experience' => '9 ans d’expérience',
                'address' => '11 quai Louis XVIII',
                'postal_code' => '33000',
                'city' => 'Bordeaux',
                'country' => 'France',
                'latitude' => '44.8481000',
                'longitude' => '-0.5665000',
                'geohash' => 'ezyzhk',
                'phone_public' => '0556001012',
                'phone_private' => '0610010012',
                'website' => 'https://www.studio-evenement.fr',
                'facebook_url' => 'https://facebook.com/studioevenement',
                'instagram_url' => 'https://instagram.com/studioevenement',
                'linkedin_url' => 'https://linkedin.com/company/studio-evenement',
                'short_description' => 'Photo, animation et ambiance sonore pour vos événements.',
                'long_description' => 'Hugo couvre mariages, soirées et événements corporate avec un positionnement premium, une direction artistique soignée et une forte réactivité.',
                'description' => 'Prestations visuelles et animation pour événements.',
                'average_rating' => '4.79',
                'reviews_count' => 23,
                'response_time_minutes' => 66,
                'completion_score' => 93,
                'verification_status' => VerificationStatusEnum::MANUALLY_VERIFIED,
                'verified_at' => $now->modify('-5 months'),
                'search_visibility' => SearchVisibilityEnum::BOOSTED,
                'is_featured' => false,
                'featured_until' => null,
            ],
            [
                'reference' => self::PROFILE_EMMA_REFERENCE,
                'user_reference' => PrestataireUserFixtures::PRESTA_EMMA_REFERENCE,
                'company_name' => 'Cours Plus',
                'legal_name' => 'Cours Plus Académie',
                'structure_type' => 'Association',
                'siren' => '804123463',
                'siret' => '80412346300043',
                'vat_number' => 'FR93804123463',
                'metier' => 'Professeure particulière',
                'experience' => '10 ans d’expérience',
                'address' => '8 rue Judaïque',
                'postal_code' => '33000',
                'city' => 'Bordeaux',
                'country' => 'France',
                'latitude' => '44.8408000',
                'longitude' => '-0.5859000',
                'geohash' => 'ezyzh2',
                'phone_public' => '0556001013',
                'phone_private' => '0610010013',
                'website' => 'https://www.cours-plus.fr',
                'facebook_url' => 'https://facebook.com/coursplus',
                'instagram_url' => 'https://instagram.com/coursplus',
                'linkedin_url' => 'https://linkedin.com/company/cours-plus',
                'short_description' => 'Soutien scolaire structuré et progression mesurable.',
                'long_description' => 'Emma accompagne collégiens, lycéens et adultes en reprise d’études avec des objectifs clairs, des supports de qualité et un vrai suivi pédagogique.',
                'description' => 'Cours particuliers et accompagnement scolaire personnalisé.',
                'average_rating' => '4.91',
                'reviews_count' => 29,
                'response_time_minutes' => 85,
                'completion_score' => 96,
                'verification_status' => VerificationStatusEnum::EMAIL_VERIFIED,
                'verified_at' => $now->modify('-70 days'),
                'search_visibility' => SearchVisibilityEnum::NORMAL,
                'is_featured' => false,
                'featured_until' => null,
            ],
            [
                'reference' => self::PROFILE_YASSINE_REFERENCE,
                'user_reference' => PrestataireUserFixtures::PRESTA_YASSINE_REFERENCE,
                'company_name' => 'Code Académie',
                'legal_name' => 'Code Académie Formation',
                'structure_type' => 'SASU',
                'siren' => '804123464',
                'siret' => '80412346400050',
                'vat_number' => 'FR11804123464',
                'metier' => 'Formateur en programmation',
                'experience' => '6 ans d’expérience',
                'address' => '16 rue Condillac',
                'postal_code' => '33000',
                'city' => 'Bordeaux',
                'country' => 'France',
                'latitude' => '44.8370000',
                'longitude' => '-0.5687000',
                'geohash' => 'ezyzh1',
                'phone_public' => '0556001014',
                'phone_private' => '0610010014',
                'website' => 'https://www.code-academie.fr',
                'facebook_url' => 'https://facebook.com/codeacademie',
                'instagram_url' => 'https://instagram.com/codeacademie',
                'linkedin_url' => 'https://linkedin.com/company/code-academie',
                'short_description' => 'Initiation au code et accompagnement vers l’autonomie.',
                'long_description' => 'Yassine propose des cours pratiques pour débutants et reconversions, centrés sur les fondamentaux, les projets concrets et la compréhension durable.',
                'description' => 'Formation informatique, web et logique de programmation.',
                'average_rating' => '4.68',
                'reviews_count' => 16,
                'response_time_minutes' => 73,
                'completion_score' => 91,
                'verification_status' => VerificationStatusEnum::PHONE_VERIFIED,
                'verified_at' => $now->modify('-35 days'),
                'search_visibility' => SearchVisibilityEnum::BOOSTED,
                'is_featured' => false,
                'featured_until' => null,
            ],
            [
                'reference' => self::PROFILE_LAURA_REFERENCE,
                'user_reference' => PrestataireUserFixtures::PRESTA_LAURA_REFERENCE,
                'company_name' => 'Équilibre Vital',
                'legal_name' => 'Équilibre Vital Bien-Être',
                'structure_type' => 'EI',
                'siren' => '804123465',
                'siret' => '80412346500068',
                'vat_number' => 'FR48804123465',
                'metier' => 'Praticienne bien-être',
                'experience' => '7 ans d’expérience',
                'address' => '3 rue des Roses',
                'postal_code' => '33700',
                'city' => 'Mérignac',
                'country' => 'France',
                'latitude' => '44.8385000',
                'longitude' => '-0.6337000',
                'geohash' => 'ezynph',
                'phone_public' => '0556001015',
                'phone_private' => '0610010015',
                'website' => 'https://www.equilibre-vital.fr',
                'facebook_url' => 'https://facebook.com/equilibrevital',
                'instagram_url' => 'https://instagram.com/equilibrevital',
                'linkedin_url' => 'https://linkedin.com/company/equilibre-vital',
                'short_description' => 'Massages, relaxation et conseils bien-être personnalisés.',
                'long_description' => 'Laura accompagne les personnes stressées ou en recherche de mieux-être avec des prestations à domicile combinant écoute, douceur et régularité.',
                'description' => 'Bien-être à domicile et accompagnement personnalisé.',
                'average_rating' => '4.83',
                'reviews_count' => 18,
                'response_time_minutes' => 51,
                'completion_score' => 94,
                'verification_status' => VerificationStatusEnum::DOCUMENTS_VERIFIED,
                'verified_at' => $now->modify('-4 months'),
                'search_visibility' => SearchVisibilityEnum::PREMIUM,
                'is_featured' => true,
                'featured_until' => $now->modify('+16 days'),
            ],
            [
                'reference' => self::PROFILE_MATTHIEU_REFERENCE,
                'user_reference' => PrestataireUserFixtures::PRESTA_MATTHIEU_REFERENCE,
                'company_name' => 'Coach Forme',
                'legal_name' => 'Coach Forme Santé',
                'structure_type' => 'SASU',
                'siren' => '804123466',
                'siret' => '80412346600076',
                'vat_number' => 'FR87804123466',
                'metier' => 'Coach sportif',
                'experience' => '11 ans d’expérience',
                'address' => '25 avenue du Parc',
                'postal_code' => '33200',
                'city' => 'Bordeaux',
                'country' => 'France',
                'latitude' => '44.8579000',
                'longitude' => '-0.6261000',
                'geohash' => 'ezynz7',
                'phone_public' => '0556001016',
                'phone_private' => '0610010016',
                'website' => 'https://www.coach-forme.fr',
                'facebook_url' => 'https://facebook.com/coachforme33',
                'instagram_url' => 'https://instagram.com/coachforme33',
                'linkedin_url' => 'https://linkedin.com/company/coach-forme',
                'short_description' => 'Coaching personnalisé à domicile ou en extérieur.',
                'long_description' => 'Matthieu construit des programmes adaptés aux objectifs, au niveau et au rythme de vie de chacun, avec un vrai suivi de progression.',
                'description' => 'Coaching sportif, mobilité et remise en forme.',
                'average_rating' => '4.89',
                'reviews_count' => 33,
                'response_time_minutes' => 44,
                'completion_score' => 97,
                'verification_status' => VerificationStatusEnum::COMPANY_VERIFIED,
                'verified_at' => $now->modify('-6 months'),
                'search_visibility' => SearchVisibilityEnum::BOOSTED,
                'is_featured' => true,
                'featured_until' => $now->modify('+21 days'),
            ],
            [
                'reference' => self::PROFILE_CHLOE_REFERENCE,
                'user_reference' => PrestataireUserFixtures::PRESTA_CHLOE_REFERENCE,
                'company_name' => 'Pet Services',
                'legal_name' => 'Pet Services Bordeaux',
                'structure_type' => 'EI',
                'siren' => '804123467',
                'siret' => '80412346700084',
                'vat_number' => 'FR19804123467',
                'metier' => 'Pet sitter',
                'experience' => '5 ans d’expérience',
                'address' => '13 rue des Fauvettes',
                'postal_code' => '33110',
                'city' => 'Le Bouscat',
                'country' => 'France',
                'latitude' => '44.8639000',
                'longitude' => '-0.5962000',
                'geohash' => 'ezynz2',
                'phone_public' => '0556001017',
                'phone_private' => '0610010017',
                'website' => 'https://www.pet-services.fr',
                'facebook_url' => 'https://facebook.com/petservices33',
                'instagram_url' => 'https://instagram.com/petservices33',
                'linkedin_url' => 'https://linkedin.com/company/pet-services',
                'short_description' => 'Garde, promenade et présence rassurante pour vos animaux.',
                'long_description' => 'Chloé propose des gardes et promenades fiables, avec un bon sens du contact animal et un suivi rassurant pour les propriétaires.',
                'description' => 'Services pour chiens et chats à domicile.',
                'average_rating' => '4.74',
                'reviews_count' => 20,
                'response_time_minutes' => 46,
                'completion_score' => 90,
                'verification_status' => VerificationStatusEnum::EMAIL_VERIFIED,
                'verified_at' => $now->modify('-50 days'),
                'search_visibility' => SearchVisibilityEnum::NORMAL,
                'is_featured' => false,
                'featured_until' => null,
            ],
            [
                'reference' => self::PROFILE_ENZO_REFERENCE,
                'user_reference' => PrestataireUserFixtures::PRESTA_ENZO_REFERENCE,
                'company_name' => 'Animaux Compagnie',
                'legal_name' => 'Animaux Compagnie Services',
                'structure_type' => 'Association',
                'siren' => '804123468',
                'siret' => '80412346800092',
                'vat_number' => 'FR62804123468',
                'metier' => 'Toiletteur à domicile',
                'experience' => '6 ans d’expérience',
                'address' => '29 rue Victor Hugo',
                'postal_code' => '33400',
                'city' => 'Talence',
                'country' => 'France',
                'latitude' => '44.8089000',
                'longitude' => '-0.5890000',
                'geohash' => 'ezynjt',
                'phone_public' => '0556001018',
                'phone_private' => '0610010018',
                'website' => 'https://www.animaux-compagnie.fr',
                'facebook_url' => 'https://facebook.com/animauxcompagnie',
                'instagram_url' => 'https://instagram.com/animauxcompagnie',
                'linkedin_url' => 'https://linkedin.com/company/animaux-compagnie',
                'short_description' => 'Toilettage et soins d’hygiène au domicile du client.',
                'long_description' => 'Enzo intervient avec douceur et méthode pour le toilettage des chiens et chats, en limitant le stress grâce au service à domicile.',
                'description' => 'Toilettage pratique et rassurant pour animaux de compagnie.',
                'average_rating' => '4.63',
                'reviews_count' => 14,
                'response_time_minutes' => 57,
                'completion_score' => 88,
                'verification_status' => VerificationStatusEnum::PHONE_VERIFIED,
                'verified_at' => $now->modify('-25 days'),
                'search_visibility' => SearchVisibilityEnum::BOOSTED,
                'is_featured' => false,
                'featured_until' => null,
            ],
            [
                'reference' => self::PROFILE_INES_REFERENCE,
                'user_reference' => PrestataireUserFixtures::PRESTA_INES_REFERENCE,
                'company_name' => 'Beauté Mobile',
                'legal_name' => 'Beauté Mobile Studio',
                'structure_type' => 'SASU',
                'siren' => '804123469',
                'siret' => '80412346900027',
                'vat_number' => 'FR32804123469',
                'metier' => 'Esthéticienne',
                'experience' => '8 ans d’expérience',
                'address' => '7 rue Sainte-Catherine',
                'postal_code' => '33000',
                'city' => 'Bordeaux',
                'country' => 'France',
                'latitude' => '44.8373000',
                'longitude' => '-0.5717000',
                'geohash' => 'ezyzh0',
                'phone_public' => '0556001019',
                'phone_private' => '0610010019',
                'website' => 'https://www.beaute-mobile.fr',
                'facebook_url' => 'https://facebook.com/beaute.mobile',
                'instagram_url' => 'https://instagram.com/beaute.mobile',
                'linkedin_url' => 'https://linkedin.com/company/beaute-mobile',
                'short_description' => 'Beauté à domicile pour le quotidien et les événements.',
                'long_description' => 'Inès propose coiffure, maquillage et prestations esthétiques avec une vraie attention au confort client, notamment avant un événement important.',
                'description' => 'Services beauté, maquillage et coiffure à domicile.',
                'average_rating' => '4.87',
                'reviews_count' => 25,
                'response_time_minutes' => 42,
                'completion_score' => 95,
                'verification_status' => VerificationStatusEnum::MANUALLY_VERIFIED,
                'verified_at' => $now->modify('-8 months'),
                'search_visibility' => SearchVisibilityEnum::PREMIUM,
                'is_featured' => true,
                'featured_until' => $now->modify('+9 days'),
            ],
            [
                'reference' => self::PROFILE_SARAH_REFERENCE,
                'user_reference' => PrestataireUserFixtures::PRESTA_SARAH_REFERENCE,
                'company_name' => 'Glam Service',
                'legal_name' => 'Glam Service Beauté',
                'structure_type' => 'EI',
                'siren' => '804123470',
                'siret' => '80412347000035',
                'vat_number' => 'FR72804123470',
                'metier' => 'Coiffeuse à domicile',
                'experience' => '9 ans d’expérience',
                'address' => '20 avenue Thiers',
                'postal_code' => '33100',
                'city' => 'Bordeaux',
                'country' => 'France',
                'latitude' => '44.8474000',
                'longitude' => '-0.5519000',
                'geohash' => 'ezyzhn',
                'phone_public' => '0556001020',
                'phone_private' => '0610010020',
                'website' => 'https://www.glam-service.fr',
                'facebook_url' => 'https://facebook.com/glamservice',
                'instagram_url' => 'https://instagram.com/glamservice',
                'linkedin_url' => 'https://linkedin.com/company/glam-service',
                'short_description' => 'Coiffure et mise en beauté à domicile avec souplesse.',
                'long_description' => 'Sarah intervient pour coiffure, préparation événementielle et mises en beauté du quotidien avec ponctualité et sens du détail.',
                'description' => 'Prestations beauté à domicile adaptées aux emplois du temps serrés.',
                'average_rating' => '4.71',
                'reviews_count' => 19,
                'response_time_minutes' => 49,
                'completion_score' => 91,
                'verification_status' => VerificationStatusEnum::COMPANY_VERIFIED,
                'verified_at' => $now->modify('-3 months'),
                'search_visibility' => SearchVisibilityEnum::NORMAL,
                'is_featured' => false,
                'featured_until' => null,
            ],
        ];

        foreach ($profiles as $data) {
            /** @var User $user */
            $user = $this->getReference($data['user_reference'], User::class);

            $profile = new PrestataireProfile();
            $profile->setAccount($user);
            $profile->setCompanyName($data['company_name']);
            $profile->setSlug(mb_strtolower($this->slugger->slug($data['company_name'])->toString()));
            $profile->setLegalName($data['legal_name']);
            $profile->setStructureType($data['structure_type']);
            $profile->setSiren($data['siren']);
            $profile->setSiret($data['siret']);
            $profile->setVatNumber($data['vat_number']);
            $profile->setAddress($data['address']);
            $profile->setPostalCode($data['postal_code']);
            $profile->setCity($data['city']);
            $profile->setCountry($data['country']);
            $profile->setLatitude($data['latitude']);
            $profile->setLongitude($data['longitude']);
            $profile->setGeohash($data['geohash']);
            $profile->setPhonePublic($data['phone_public']);
            $profile->setPhonePrivate($data['phone_private']);
            $profile->setWebsite($data['website']);
            $profile->setFacebookUrl($data['facebook_url']);
            $profile->setInstagramUrl($data['instagram_url']);
            $profile->setLinkedinUrl($data['linkedin_url']);
            $profile->setShortDescription($data['short_description']);
            $profile->setLongDescription($data['long_description']);
            $profile->setDescription($data['description']);
            $profile->setMetier($data['metier']);
            $profile->setExperience($data['experience']);
            $profile->setProfileStatus(PrestataireProfileStatusEnum::ACTIVE);
            $profile->setVerificationStatus($data['verification_status']);
            $profile->setCompletionScore($data['completion_score']);
            $profile->setAverageRating($data['average_rating']);
            $profile->setReviewsCount($data['reviews_count']);
            $profile->setResponseTimeMinutes($data['response_time_minutes']);
            $profile->setIsFeatured($data['is_featured']);
            $profile->setFeaturedUntil($data['featured_until']);
            $profile->setSearchVisibility($data['search_visibility']);
            $profile->setVerifiedAt($data['verified_at']);
            $profile->setCreatedAt($now->modify('-1 year'));
            $profile->setUpdatedAt($now->modify('-2 days'));

            $manager->persist($profile);

            $this->addReference($data['reference'], $profile);
        }

        $manager->flush();
    }

    public function getDependencies(): array
    {
        return [
            PrestataireUserFixtures::class,
        ];
    }
}
