# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
# See also https://symfony.com/doc/current/service_container/import.html

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    FRANKENPHP_HOT_RELOAD: '%env(FRANKENPHP_HOT_RELOAD)%'
    app.elasticsearch_host: '%env(ELASTICSEARCH_HOST)%'
    app.elasticsearch_user: '%env(ELASTICSEARCH_USER)%'
    app.elasticsearch_password: '%env(ELASTICSEARCH_PASSWORD)%'
    app.elasticsearch_verify_tls: '%env(bool:ELASTICSEARCH_VERIFY_TLS)%'
    app.maintenance_mode: '%env(bool:MAINTENANCE_MODE)%'
    app.maintenance_secret: '%env(default::MAINTENANCE_SECRET)%'
    app.insee_sirene.base_url: '%env(INSEE_SIRENE_BASE_URL)%'
    app.insee_sirene.api_key: '%env(INSEE_SIRENE_API_KEY)%'
    app.stripe.secret_key: '%env(default::STRIPE_SECRET_KEY)%'
    app.stripe.public_key: '%env(default::STRIPE_PUBLIC_KEY)%'
    app.stripe.webhook_secret: '%env(default::STRIPE_WEBHOOK_SECRET)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            string $host: '%app.elasticsearch_host%'
            string $username: '%app.elasticsearch_user%'
            string $password: '%app.elasticsearch_password%'
            bool $verifyTls: '%app.elasticsearch_verify_tls%'
            $realtimeBaseUrl: '%env(string:REALTIME_BASE_URL)%'
            $internalToken: '%env(string:REALTIME_INTERNAL_TOKEN)%'
            string $sireneBaseUrl: '%app.insee_sirene.base_url%'
            string $sireneApiKey: '%app.insee_sirene.api_key%'
            string $stripeSecretKey: '%app.stripe.secret_key%'
            string $webhookSecret: '%app.stripe.webhook_secret%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\EventSubscriber\MaintenanceSubscriber:
        arguments:
            $maintenanceMode: '%app.maintenance_mode%'
            $maintenanceSecret: '%app.maintenance_secret%'
